
export const inspectionData = [
  {
    id:'1',
    date: 'Monday, 02 March 2020',
    isBooked: 'No',
    terminal: 'Early',
    unknownNumber: 0,
    bookingStatus: 'Confirmed 3/2/2020 10:17 AM',
    inspectionStatus: 'Cancelled',
    accessibility: false,
    buildingService: false,
    completion: false,
    fireSafety: true,
    foundation: false,
    fw: false,
    general: false,
    oversiteDpc: false,
    protection: false,
    soundInsulation: false,
    superStructure: false,
    sw: false,
    thermalInsulation:false,
    firstPlot: true,
    secondPlot: false,
    thirdPlot: false,
    fourthPlot: false,
    fifthPlot: false,
    sixthPlot: false,
    seventhPlot: false,
    eighthPlot: false
  },
  {
    id:'2',
    date: 'Thursday, 23 January 2020',
    isBooked: 'Yes',
    terminal: '',
    unknownNumber: '',
    bookingStatus: 'Confirmed 1/22/2020 1:12 PM',
    inspectionStatus: 'Cancelled',
    accessibility: false,
    buildingService: true,
    completion: true,
    fireSafety: false,
    foundation: false,
    fw: false,
    general: false,
    oversiteDpc: false,
    protection: false,
    soundInsulation: false,
    superStructure: false,
    sw: false,
    thermalInsulation:false,
    firstPlot: false,
    secondPlot: false,
    thirdPlot: true,
    fourthPlot: false,
    fifthPlot: false,
    sixthPlot: false,
    seventhPlot: false,
    eighthPlot: false
  },
  {
    id:'3',
    date: 'Thursday, 23 January 2020',
    isBooked: 'No',
    terminal: 'Early',
    unknownNumber: '30',
    bookingStatus: 'Confirmed 1/22/2020 3:37 PM',
    inspectionStatus: 'Not Available',
    accessibility: true,
    buildingService: true,
    completion: false,
    fireSafety: false,
    foundation: false,
    fw: false,
    general: false,
    oversiteDpc: false,
    protection: false,
    soundInsulation: false,
    superStructure: false,
    sw: false,
    thermalInsulation:false,
    firstPlot: false,
    secondPlot: false,
    thirdPlot: true,
    fourthPlot: false,
    fifthPlot: false,
    sixthPlot: false,
    seventhPlot: false,
    eighthPlot: false
  },
  {
    id:'4',
    date: 'Wednesday, 22 January 2020',
    isBooked: 'No',
    terminal: "Don't Mind",
    unknownNumber: '30',
    bookingStatus: 'Confirmed 1/22/2020 7:47:53 AM',
    inspectionStatus: 'Cancelled',
    accessibility: false,
    buildingService: true,
    completion: false,
    fireSafety: false,
    foundation: false,
    fw: false,
    general: false,
    oversiteDpc: false,
    protection: false,
    soundInsulation: false,
    superStructure: false,
    sw: false,
    thermalInsulation:false,
    firstPlot: false,
    secondPlot: false,
    thirdPlot: true,
    fourthPlot: false,
    fifthPlot: false,
    sixthPlot: false,
    seventhPlot: false,
    eighthPlot: false
  },
  {
    id:'5',
    date: '',
    isBooked: 'No',
    terminal: "",
    unknownNumber: '',
    bookingStatus: 'Unsubmitted',
    inspectionStatus: 'Not Available',
    accessibility: false,
    buildingService: false,
    completion: false,
    fireSafety: false,
    foundation: false,
    fw: false,
    general: false,
    oversiteDpc: false,
    protection: false,
    soundInsulation: false,
    superStructure: false,
    sw: false,
    thermalInsulation:false,
    firstPlot: false,
    secondPlot: false,
    thirdPlot: false,
    fourthPlot: false,
    fifthPlot: false,
    sixthPlot: false,
    seventhPlot: false,
    eighthPlot: false
  },
];
